//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public sbyte userType { get; set; }
    }
}
