//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer
    {
        public int id { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string name { get; set; }
        public string contactNumber { get; set; }
        public sbyte userType { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
