//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.match = new HashSet<match>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string venue { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual ICollection<match> match { get; set; }
    }
}
