//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobfairContext : DbContext
    {
        public jobfairContext()
            : base("name=jobfairContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<@event> @event { get; set; }
        public DbSet<jobseeker> jobseeker { get; set; }
        public DbSet<jobseekerskill> jobseekerskill { get; set; }
        public DbSet<match> match { get; set; }
        public DbSet<skill> skill { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<vacancy> vacancy { get; set; }
        public DbSet<workhistory> workhistory { get; set; }
        public DbSet<employer> employer { get; set; }
        public DbSet<language> language { get; set; }
        public DbSet<boolean> boolean { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<location> location { get; set; }
        public DbSet<race> race { get; set; }
        public DbSet<salary_range> salary_range { get; set; }
        public DbSet<qualification> qualification { get; set; }
    }
}
