//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobfairContext : DbContext
    {
        public jobfairContext()
            : base("name=jobfairContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<boolean> boolean { get; set; }
        public DbSet<employer> employer { get; set; }
        public DbSet<@event> @event { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<jobseeker> jobseeker { get; set; }
        public DbSet<jobseekersoftskill> jobseekersoftskill { get; set; }
        public DbSet<jobseekertechskill> jobseekertechskill { get; set; }
        public DbSet<language> language { get; set; }
        public DbSet<location> location { get; set; }
        public DbSet<match> match { get; set; }
        public DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public DbSet<my_aspnet_paths> my_aspnet_paths { get; set; }
        public DbSet<my_aspnet_personalizationallusers> my_aspnet_personalizationallusers { get; set; }
        public DbSet<my_aspnet_personalizationperuser> my_aspnet_personalizationperuser { get; set; }
        public DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public DbSet<my_aspnet_sitemap> my_aspnet_sitemap { get; set; }
        public DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public DbSet<qualification> qualification { get; set; }
        public DbSet<race> race { get; set; }
        public DbSet<salary_range> salary_range { get; set; }
        public DbSet<skill> skill { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<vacancy> vacancy { get; set; }
        public DbSet<vacancysoftskill> vacancysoftskill { get; set; }
        public DbSet<vacancytechskill> vacancytechskill { get; set; }
        public DbSet<webpages_membership> webpages_membership { get; set; }
        public DbSet<webpages_oauthmembership> webpages_oauthmembership { get; set; }
        public DbSet<webpages_oauthtoken> webpages_oauthtoken { get; set; }
        public DbSet<webpages_roles> webpages_roles { get; set; }
        public DbSet<webpages_usersinroles> webpages_usersinroles { get; set; }
        public DbSet<workhistory> workhistory { get; set; }
    }
}
