//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobseekersoftskill
    {
        public int id { get; set; }
        public int skillid { get; set; }
        public string ownerEmail { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    
        public virtual jobseeker jobseeker { get; set; }
        public virtual skill skill { get; set; }
    }
}
