//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobseeker
    {
        public jobseeker()
        {
            this.jobseekersoftskill = new HashSet<jobseekersoftskill>();
            this.jobseekertechskill = new HashSet<jobseekertechskill>();
            this.match = new HashSet<match>();
            this.workhistory = new HashSet<workhistory>();
        }
    
        public string email { get; set; }
        public string firstName { get; set; }
        public string surname { get; set; }
        public string highestQualification { get; set; }
        public string contactNumber { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public string inNo { get; set; }
        public string firstLanguage { get; set; }
        public string secondLanguage { get; set; }
        public bool disability { get; set; }
        public string location { get; set; }
        public string race { get; set; }
        public string gender { get; set; }
        public sbyte userType { get; set; }
        public bool driversLicense { get; set; }
        public bool criminalRecord { get; set; }
        public Nullable<bool> workPermit { get; set; }
        public Nullable<int> salaryMin { get; set; }
        public string preferredPosition { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual ICollection<jobseekersoftskill> jobseekersoftskill { get; set; }
        public virtual ICollection<jobseekertechskill> jobseekertechskill { get; set; }
        public virtual ICollection<match> match { get; set; }
        public virtual ICollection<workhistory> workhistory { get; set; }
    }
}
