//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        public string employerEmail { get; set; }
        public string jobseekerEmail { get; set; }
        public int eventId { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual jobseeker jobseeker { get; set; }
        public virtual employer employer { get; set; }
    }
}
