//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_personalizationperuser
    {
        public int id { get; set; }
        public int applicationId { get; set; }
        public string pathId { get; set; }
        public Nullable<int> userId { get; set; }
        public byte[] pageSettings { get; set; }
        public System.DateTime lastUpdatedDate { get; set; }
    }
}
