//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_paths
    {
        public int applicationId { get; set; }
        public string pathId { get; set; }
        public string path { get; set; }
        public string loweredPath { get; set; }
    }
}
