//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public skill()
        {
            this.jobseekerskill = new HashSet<jobseekerskill>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<jobseekerskill> jobseekerskill { get; set; }
    }
}
