//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        public vacancy()
        {
            this.vacancytechskill = new HashSet<vacancytechskill>();
            this.vacancysoftskill = new HashSet<vacancysoftskill>();
        }
    
        public int id { get; set; }
        public string ownerEmail { get; set; }
        public string lowestQualification { get; set; }
        public string location { get; set; }
        public Nullable<int> salaryMin { get; set; }
        public Nullable<bool> driversLicense { get; set; }
        public Nullable<bool> criminalRecord { get; set; }
        public string gender { get; set; }
        public Nullable<bool> disability { get; set; }
        public string race { get; set; }
        public string name { get; set; }
        public string language { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual ICollection<vacancytechskill> vacancytechskill { get; set; }
        public virtual ICollection<vacancysoftskill> vacancysoftskill { get; set; }
    }
}
