//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JFLatest
{
    using System;
    using System.Collections.Generic;
    
    public partial class workhistory
    {
        public int id { get; set; }
        public string ownerEmail { get; set; }
        public string position { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string employer { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string WorkHistorycol { get; set; }
    
        public virtual jobseeker jobseeker { get; set; }
    }
}
